### ISSUE TITLE
Can't compile, `! Package xkeyval Error: `jekyllData' undefined in families `markdownOptions'.`

### ISSUE THREAD

**Issue by GladOSkar** [TeXhackse/37c3-beamer#2]
Hi! Not sure what i'm doing wrong, but after copiling and letting it run for a few seconds, i get the following output:

```
(/usr/share/texmf-dist/tex/generic/markdown/markdown.tex)

! Package xkeyval Error: `jekyllData' undefined in families `markdownOptions'.

See the xkeyval package documentation for explanation.
Type  H <return>  for immediate help.
```

My Versions: `texlive-20210325_7`

Do you maybe know what's wrong? Thanks!

**Comment by TeXhackse** [comment]
You markdown package is too old, it doesn't support that option, if I remember correctly, we implemented that some time in 2022.

**Comment by GladOSkar** [comment]
Ah okay too bad. Well thanks anyway! Have a great new year!
